// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Images", testImages)
}

func TestDelete(t *testing.T) {
	t.Run("Images", testImagesDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Images", testImagesQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Images", testImagesSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Images", testImagesExists)
}

func TestFind(t *testing.T) {
	t.Run("Images", testImagesFind)
}

func TestBind(t *testing.T) {
	t.Run("Images", testImagesBind)
}

func TestOne(t *testing.T) {
	t.Run("Images", testImagesOne)
}

func TestAll(t *testing.T) {
	t.Run("Images", testImagesAll)
}

func TestCount(t *testing.T) {
	t.Run("Images", testImagesCount)
}

func TestHooks(t *testing.T) {
	t.Run("Images", testImagesHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Images", testImagesInsert)
	t.Run("Images", testImagesInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Images", testImagesReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Images", testImagesReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Images", testImagesSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Images", testImagesUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Images", testImagesSliceUpdateAll)
}
